### ISSUE TITLE
Add CITATION.cff file

### ISSUE THREAD

**Issue by vterron** [akdiaz/LPD#19]
TL; DR: https://twitter.com/natfriedman/status/1420122675813441540

> We’ve just added built-in citation support to GitHub so researchers and scientists can more easily receive acknowledgments for their contributions to software.
> 
> Just push a CITATION.cff file and we’ll add a handy widget to the repo sidebar for you.

- [About CITATION files](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) page on the GitHub docs.
- [Citation File Format (CFF)](https://citation-file-format.github.io/).
- [GitHub commits of `.cff` files  on GitHub](https://github.com/search?q=CITATION.cff&type=commits).

**Comment by akdiaz** [comment]
Citation file added
